# Generated by Django 3.2.6 on 2021-09-18 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adgroup_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Paused', 'Paused')], default='Enabled', max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Paused', 'Paused')], default='Enabled', max_length=21)),
                ('match_type', models.CharField(choices=[('Exact', 'Exact'), ('Phrase', 'Phrase'), ('Broad', 'Broad')], default='Exact', max_length=21)),
                ('adgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='rest.adgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Paused', 'Paused')], default='Paused', max_length=21)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='rest.account')),
            ],
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adgroups', to='rest.campaign'),
        ),
    ]
